package schemagen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func GenerateRegistry(lock *Lockfile, outDir string) error {
	registryPath := filepath.Join(outDir, "registry.go")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	type entry struct {
		uuid        string
		code        string
		subCode     string // sub-migration entries for squash
	}
	var plain, squash []entry

	for name, ref := range lock.Schemas {
		safeName := SafeIdent(name)

		// Bootstrap entry: 0.0.0 → first history version.
		if len(ref.History) > 0 {
			firstVer := ref.History[0].Version
			firstFile := ref.History[0].MigrationFile
			funcName := fmt.Sprintf("%s_0_0_0_to_%s", safeName,
				strings.ReplaceAll(firstVer, ".", "_"))
			uuid := MigrationUUID(firstFile)
			plain = append(plain, entry{
				uuid: uuid,
				code: fmt.Sprintf(`	{UUID: %q, Collection: %q, From: "0.0.0", To: %q, File: %q, Plan: %s}`,
					uuid, name, firstVer, firstFile, funcName),
			})
		}

		// Current migration (squash or plain).
		if len(ref.SubMigrations) > 0 {
			// Squash entry: emit SubMigrations metadata.
			curUUID := MigrationUUID(ref.MigrationFile)
			fromVer := ref.History[0].Version
			funcName := fmt.Sprintf("%s_%s_to_%s", safeName,
				strings.ReplaceAll(fromVer, ".", "_"),
				strings.ReplaceAll(ref.Version, ".", "_"))

			var subCodes []string
			for _, subFile := range ref.SubMigrations {
				subUUID := MigrationUUID(subFile)
				subCodes = append(subCodes, fmt.Sprintf(`		{UUID: %q, File: %q}`,
					subUUID, subFile))
			}
			subCodeStr := fmt.Sprintf(`[]Migration{
%s,
	}`, strings.Join(subCodes, ",\n"))

			squash = append(squash, entry{
				uuid: curUUID,
				code: fmt.Sprintf(`	{UUID: %q, Collection: %q, From: %q, To: %q, File: %q, Plan: %s, SubMigrations: %s}`,
					curUUID, name, fromVer, ref.Version, ref.MigrationFile, funcName, subCodeStr),
			})
		} else if len(ref.History) > 0 {
			// Plain migration derived from history.
			for i, h := range ref.History {
				subFrom := h.Version
				var subTo, migFile string
				if i+1 < len(ref.History) {
					subTo = ref.History[i+1].Version
					migFile = ref.History[i+1].MigrationFile
				} else {
					subTo = ref.Version
					migFile = ref.MigrationFile
				}
				if migFile == "" {
					continue
				}
				subUUID := MigrationUUID(migFile)
				subFuncName := fmt.Sprintf("%s_%s_to_%s", safeName,
					strings.ReplaceAll(subFrom, ".", "_"),
					strings.ReplaceAll(subTo, ".", "_"))
				plain = append(plain, entry{
					uuid: subUUID,
					code: fmt.Sprintf(`	{UUID: %q, Collection: %q, From: %q, To: %q, File: %q, Plan: %s}`,
						subUUID, name, subFrom, subTo, migFile, subFuncName),
				})
			}
		} else {
			// First generation — no history.
			uuid := MigrationUUID(ref.MigrationFile)
			funcName := fmt.Sprintf("%s_0_0_0_to_%s", safeName,
				strings.ReplaceAll(ref.Version, ".", "_"))
			plain = append(plain, entry{
				uuid: uuid,
				code: fmt.Sprintf(`	{UUID: %q, Collection: %q, From: "0.0.0", To: %q, File: %q, Plan: %s}`,
					uuid, name, ref.Version, ref.MigrationFile, funcName),
			})
		}
	}

	if len(plain) == 0 && len(squash) == 0 {
		return nil
	}

	// Sort plain and squash entries by UUID.
	sort.Slice(plain, func(i, j int) bool { return plain[i].uuid < plain[j].uuid })
	sort.Slice(squash, func(i, j int) bool { return squash[i].uuid < squash[j].uuid })

	var plainCode, squashCode string
	if len(plain) > 0 {
		var codes []string
		for _, e := range plain {
			codes = append(codes, e.code)
		}
		plainCode = strings.Join(codes, ",\n")
	}
	if len(squash) > 0 {
		var codes []string
		for _, e := range squash {
			codes = append(codes, e.code)
		}
		squashCode = "{\n" + strings.Join(codes, ",\n") + ",\n}"
	} else {
		squashCode = "(nil)"
	}

	code := fmt.Sprintf(`// Code generated by anansi schema migrate. DO NOT EDIT.
package migrations

import (
	"context"
	"fmt"
	"sort"

	"github.com/asaidimu/go-anansi/v7/core/persistence/base"
	"github.com/asaidimu/go-anansi/v7/core/schema/definition"
)

// Migration describes a single schema migration.
type Migration struct {
	UUID          string
	Collection    string
	From          string
	To            string
	File          string
	Plan          func() *base.MigrationPlan
	SubMigrations []Migration // populated for squash entries
}

// Plain holds all plain (non-squashed) migrations sorted by UUID.
var Plain = []Migration{
%s,
}

// Squash holds all squash migrations sorted by UUID.
var Squash = []Migration%s

// All merges Plain and Squash, sorted by UUID, and returns them as a single slice.
func All() []Migration {
	all := make([]Migration, 0, len(Plain)+len(Squash))
	all = append(all, Plain...)
	all = append(all, Squash...)
	sort.Slice(all, func(i, j int) bool { return all[i].UUID < all[j].UUID })
	return all
}

// Apply reconciles the database with every registered migration.
//
// For each collection:
//   - If it does not exist, it is created from the first migration's
//     target schema, then remaining migrations are applied in order.
//   - If it exists at a version that matches a migration's From, that
//     migration (and any subsequent pending ones) is applied.
//
// Usage:
//
//	p, cleanup := anansi.Playground(...)
//	defer cleanup()
//	migrations.Apply(ctx, p)
func Apply(ctx context.Context, p base.Persistence) error {
	collMigrations := make(map[string][]Migration)
	for _, m := range All() {
		collMigrations[m.Collection] = append(collMigrations[m.Collection], m)
	}

	for _, ms := range collMigrations {
		name := ms[0].Collection

		exists, err := p.HasCollection(ctx, name)
		if err != nil {
			return fmt.Errorf("check %%s: %%w", name, err)
		}

		if !exists {
			// Bootstrap from the first migration's target, then apply the rest.
			first := ms[0].Plan().Target
			if err := p.CreateCollections(ctx, []*definition.Schema{first}); err != nil {
				return fmt.Errorf("create %%s: %%w", name, err)
			}
			ms = ms[1:] // don't re-apply the bootstrap migration
		}

		for _, m := range ms {
			sc, err := p.Schema(ctx, name)
			if err != nil {
				return fmt.Errorf("schema %%s: %%w", name, err)
			}
			if sc.Version.String() != m.From {
				continue
			}
			plan := m.Plan()
			if _, err := p.Migrate(ctx, name, plan, nil); err != nil {
				return fmt.Errorf("migrate %%s %%s->%%s: %%w", name, m.From, m.To, err)
			}
		}
	}
	return nil
}
`, plainCode, squashCode)

	return os.WriteFile(registryPath, []byte(code), 0644)
}
