package schemagen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
	"github.com/asaidimu/go-anansi/v8/core/schema/meta"
)

func RunScaffold(dir string, dryRun bool, anansiVersion string) error {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return fmt.Errorf("resolve path: %w", err)
	}

	modulePath := filepath.Base(abs)

	schemasDir := filepath.Join(abs, "schemas")
	migrationsDir := filepath.Join(abs, "migrations")

	if dryRun {
		fmt.Printf("would scaffold anansi project in %s\n", abs)
		fmt.Printf("  would create: %s/\n", schemasDir)
		fmt.Printf("  would create: %s/\n", migrationsDir)
		fmt.Printf("  would create: %s/go.mod\n", abs)
		fmt.Printf("  would create: %s/main.go\n", abs)
		fmt.Printf("  would create: %s/anansi.json\n", abs)
		fmt.Printf("  would create: %s/example.schema.json\n", schemasDir)
		fmt.Printf("  would create: %s/schemas.lock.json\n", abs)
		fmt.Printf("  would create: %s/AGENTS.md\n", abs)
		fmt.Println()
		fmt.Println("after scaffolding, run:")
		fmt.Printf("  cd %s && go mod tidy && go run .\n", dir)
		return nil
	}

	// Refuse to scaffold into a non-empty directory.
	if entries, err := os.ReadDir(abs); err == nil && len(entries) > 0 {
		return fmt.Errorf("refusing to scaffold into non-empty directory %s", abs)
	}

	// Create directories
	for _, p := range []string{abs, schemasDir, migrationsDir} {
		if err := os.MkdirAll(p, 0755); err != nil {
			return fmt.Errorf("create %s: %w", p, err)
		}
	}

	// go.mod
	gomod := fmt.Sprintf(`module %s

go 1.21

require github.com/asaidimu/go-anansi/v8 %s
`, modulePath, anansiVersion)
	if err := os.WriteFile(filepath.Join(abs, "go.mod"), []byte(gomod), 0644); err != nil {
		return fmt.Errorf("write go.mod: %w", err)
	}

	// main.go
	migrationsPkg := modulePath + "/migrations"
	tpl := `package main

import (
	"context"
	"fmt"
	"log"
	"time"

	anansi "github.com/asaidimu/go-anansi/v8"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/query"
	"MPKG"
	_ "github.com/mattn/go-sqlite3"
)

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	p, cleanup, err := anansi.Playground(anansi.PlaygroundConfig{
		DBPath: "data.db",
	})
	if err != nil {
		log.Fatalf("playground: %v", err)
	}
	defer cleanup()

	if err := migrations.Apply(ctx, p); err != nil {
		log.Fatalf("apply migrations: %v", err)
	}
	fmt.Println("migrations applied — database is ready")

	coll, err := p.Collection(ctx, "Example")
	if err != nil {
		log.Fatalf("get collection: %v", err)
	}

	_, err = coll.CreateMany(ctx, []*data.Document{
		data.MustNewDocument(map[string]any{"name": "hello world"}),
	})
	if err != nil {
		log.Fatalf("create: %v", err)
	}
	fmt.Println("created a sample document")

	r, err := coll.Read(ctx, &query.Query{})
	if err != nil {
		log.Fatalf("read: %v", err)
	}
	fmt.Printf("collection %q has %d document(s)\n", "Example", len(r.Data))
}`
	mainSrc := strings.ReplaceAll(tpl, "MPKG", migrationsPkg)
	if err := os.WriteFile(filepath.Join(abs, "main.go"), []byte(mainSrc), 0644); err != nil {
		return fmt.Errorf("write main.go: %w", err)
	}

	// anansi.json
	cfg := DefaultConfig()
	cfgData, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	if err := os.WriteFile(filepath.Join(abs, "anansi.json"), cfgData, 0644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	// Example schema — parse, set version, normalize, then write to disk
	// so the JSON always includes a version field.
	exampleRaw := `{
  "name": "Example",
  "description": "Example schema — replace with your own",
  "fields": {
    "019d7775-6563-7c55-a6f3-ac8f087d89d1": {
      "name": "name",
      "type": "string",
      "required": true
    }
  }
}`
	schema, err := definition.FromJSON([]byte(exampleRaw))
	if err != nil {
		return fmt.Errorf("parse example schema: %w", err)
	}
	if schema.Version == nil {
		schema.Version = common.MustNewVersion("0.1.0")
	}
	meta.NormalizeSchema(schema)
	exampleJSON := schema.ToJSON()

	examplePath := filepath.Join(schemasDir, "example.schema.json")
	if err := os.WriteFile(examplePath, exampleJSON, 0644); err != nil {
		return fmt.Errorf("write example schema: %w", err)
	}

	// Generate migration file
	safeName := SafeIdent("Example")
	exampleVer := schema.Version.String()
	verIdent := strings.ReplaceAll(exampleVer, ".", "_")
	funcName := fmt.Sprintf("%s_0_0_0_to_%s", safeName, verIdent)
	targetFunc := fmt.Sprintf("target_%s_%s", safeName, verIdent)
	fileName := fmt.Sprintf("%s_%s_minor.go",
		strings.ReplaceAll(exampleVer, ".", "_"), safeName)

	migSrc := fmt.Sprintf(`// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: schemas/example.schema.json
package migrations

import (
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// %[1]s returns a migration plan (0.0.0 → %[2]s).
func %[1]s() *base.MigrationPlan {
	m := &base.MigrationPlan{
		Description: "initial schema",
		Target:      %[3]s(),
		VersionBump: definition.BumpMinor,
	}
	return m
}

var %[3]s_json = []byte(%[4]q)

func %[3]s() *definition.Schema {
	s, err := definition.FromJSON(%[3]s_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
`, funcName, exampleVer, targetFunc, string(exampleJSON))

	if err := os.WriteFile(filepath.Join(migrationsDir, fileName), []byte(migSrc), 0644); err != nil {
		return fmt.Errorf("write migration file: %w", err)
	}

	// Build lockfile
	hash := ContentHash(exampleJSON)
	lock := &Lockfile{
		Version: "1",
		Schemas: map[string]*SchemaRef{
			"Example": {
				Path:          "schemas/example.schema.json",
				Hash:          hash,
				Version:       exampleVer,
				Schema:        schema,
				MigrationFile: fileName,
			},
		},
	}

	if err := WriteLockfile(filepath.Join(abs, "schemas.lock.json"), lock); err != nil {
		return fmt.Errorf("write lockfile: %w", err)
	}

	if err := GenerateRegistry(lock, migrationsDir); err != nil {
		return fmt.Errorf("generate registry: %w", err)
	}

	// AGENTS.md
	if err := RunAgents(abs, false); err != nil {
		return fmt.Errorf("write AGENTS.md: %w", err)
	}

	fmt.Printf("scaffolded anansi project in %s\n", abs)
	fmt.Printf("  created: %s/go.mod\n", abs)
	fmt.Printf("  created: %s/main.go\n", abs)
	fmt.Printf("  created: %s\n", filepath.Join(abs, "anansi.json"))
	fmt.Printf("  created: %s/\n", schemasDir)
	fmt.Printf("  created: %s/\n", migrationsDir)
	fmt.Printf("  created: %s\n", examplePath)
	fmt.Printf("  created: %s\n", filepath.Join(abs, "schemas.lock.json"))
	fmt.Printf("  created: %s\n", filepath.Join(migrationsDir, fileName))
	fmt.Printf("  created: %s\n", filepath.Join(migrationsDir, "registry.go"))
	fmt.Printf("  created: %s\n", filepath.Join(abs, "AGENTS.md"))
	fmt.Println()
	fmt.Println("next steps:")
	fmt.Printf("  cd %s && go mod tidy && go run .\n", dir)
	return nil
}
