package query

import "github.com/asaidimu/go-anansi/v7/core/common"

// Pre-defined errors for the query package.
var (
	ErrQueryFilterMustHaveOneFieldPopulated = common.NewSystemError("ERR_QUERY_FILTER_MUST_HAVE_ONE_FIELD_POPULATED", "exactly one of Condition, Group, or TextSearchQuery must be set")
	ErrQueryFilterMutuallyExclusive         = common.NewSystemError("ERR_QUERY_FILTER_MUTUALLY_EXCLUSIVE", "QueryFilter cannot have both condition and group populated - they are mutually exclusive")
	ErrFilterConditionFieldEmpty            = common.NewSystemError("ERR_QUERY_FILTER_CONDITION_FIELD_EMPTY", "filter condition field cannot be empty")
	ErrUnknownComparisonOperator            = common.NewSystemError("ERR_QUERY_UNKNOWN_COMPARATOR", "unknown comparison operator")
	ErrTextSearchQueryEmpty                 = common.NewSystemError("ERR_QUERY_TEXT_SEARCH_QUERY_EMPTY", "text search query cannot be empty")
	ErrTextSearchFieldsEmpty                = common.NewSystemError("ERR_QUERY_TEXT_SEARCH_FIELDS_EMPTY", "text search must specify at least one field")
	ErrInvalidSortDirection                 = common.NewSystemError("ERR_QUERY_INVALID_SORT_DIRECTION", "invalid sort direction")
	ErrPaginationLimitNotPositive           = common.NewSystemError("ERR_QUERY_PAGINATION_LIMIT_NOT_POSITIVE", "pagination limit must be positive")
	ErrPaginationOffsetNegative             = common.NewSystemError("ERR_QUERY_PAGINATION_OFFSET_NEGATIVE", "pagination offset cannot be negative")
	ErrInvalidFunctionArgument              = common.NewSystemError("ERR_QUERY_INVALID_FUNCTION_ARGUMENT", "invalid function argument")
	ErrInvalidNestedProjection              = common.NewSystemError("ERR_QUERY_INVALID_NESTED_PROJECTION", "invalid nested projection")
	ErrFailedToMarshalRecordForDistinct     = common.NewSystemError("ERR_QUERY_FAILED_TO_MARSHAL_RECORD_FOR_DISTINCT", "failed to marshal record for distinct check")
	ErrFailedToMarshalDistinctKey           = common.NewSystemError("ERR_QUERY_FAILED_TO_MARSHAL_DISTINCT_KEY", "failed to marshal distinct key")
	ErrUnsupportedAggregationType           = common.NewSystemError("ERR_QUERY_UNSUPPORTED_AGGREGATION_TYPE", "unsupported aggregation type")
	ErrStreamingJoinProjection              = common.NewSystemError("ERR_QUERY_STREAMING_JOIN_PROJECTION", "projection error during streaming join")
	ErrFailedToApplyNestedExclusion         = common.NewSystemError("ERR_QUERY_FAILED_TO_APPLY_NESTED_EXCLUSION", "failed to apply nested exclusion")
	ErrFailedToApplyNestedProjection        = common.NewSystemError("ERR_QUERY_FAILED_TO_APPLY_NESTED_PROJECTION", "failed to apply nested projection")
	ErrQueryCannotBeNil                     = common.NewSystemError("ERR_QUERY_CANNOT_BE_NIL", "query cannot be nil")
	ErrTargetNameEmpty                      = common.NewSystemError("ERR_QUERY_TARGET_NAME_EMPTY", "target name cannot be empty when target is specified")
	ErrSortFieldEmpty                       = common.NewSystemError("ERR_QUERY_SORT_FIELD_EMPTY", "sort field cannot be empty")
	ErrInvalidPaginationType                = common.NewSystemError("ERR_QUERY_INVALID_PAGINATION_TYPE", "invalid pagination type")
	ErrFilterCannotBeNil                    = common.NewSystemError("ERR_QUERY_FILTER_CANNOT_BE_NIL", "filter cannot be nil")
	ErrFilterGroupEmpty                     = common.NewSystemError("ERR_QUERY_FILTER_GROUP_EMPTY", "filter group must have at least one condition")
	ErrTextSearchNotImplemented             = common.NewSystemError("ERR_QUERY_TEXT_SEARCH_NOT_IMPLEMENTED", "text search is not implemented in this version of the helper")
	ErrFieldRefTypeInvalid                  = common.NewSystemError("ERR_QUERY_FIELD_REF_TYPE_INVALID", "field reference type must be 'field'")
	ErrFieldRefFieldEmpty                   = common.NewSystemError("ERR_QUERY_FIELD_REF_FIELD_EMPTY", "field reference field cannot be empty")
	ErrSubqueryValueTypeInvalid             = common.NewSystemError("ERR_QUERY_SUBQUERY_VALUE_TYPE_INVALID", "subquery value type must be 'subquery'")
	ErrSubqueriesNotSupported               = common.NewSystemError("ERR_QUERY_SUBQUERIES_NOT_SUPPORTED", "subqueries are not supported by this in-memory query helper")
	ErrFunctionCallNameEmpty                = common.NewSystemError("ERR_QUERY_FUNCTION_CALL_NAME_EMPTY", "function call function name cannot be empty")
	ErrFilterValueMultipleTypes             = common.NewSystemError("ERR_QUERY_FILTER_VALUE_MULTIPLE_TYPES", "FilterValue can only have one type of value set")
	ErrProjectionConfigNil                  = common.NewSystemError("ERR_QUERY_PROJECTION_CONFIG_NIL", "projection configuration cannot be nil")
	ErrProjectionIncludeExcludeConflict     = common.NewSystemError("ERR_QUERY_PROJECTION_INCLUDE_EXCLUDE_CONFLICT", "cannot use both include and exclude in the same projection")
	ErrProjectionIncludeFieldEmpty          = common.NewSystemError("ERR_QUERY_PROJECTION_INCLUDE_FIELD_EMPTY", "projection include field name cannot be empty")
	ErrProjectionExcludeFieldEmpty          = common.NewSystemError("ERR_QUERY_PROJECTION_EXCLUDE_FIELD_EMPTY", "projection exclude field name cannot be empty")
	ErrComputedFieldTypeInvalid             = common.NewSystemError("ERR_QUERY_COMPUTED_FIELD_TYPE_INVALID", "computed field expression type must be 'computed_field'")
	ErrComputedFieldExpressionNil           = common.NewSystemError("ERR_QUERY_COMPUTED_FIELD_EXPRESSION_NIL", "computed field expression cannot be nil")
	ErrComputedFieldAliasEmpty              = common.NewSystemError("ERR_QUERY_COMPUTED_FIELD_ALIAS_EMPTY", "computed field alias cannot be empty")
	ErrCaseExpressionTypeInvalid            = common.NewSystemError("ERR_QUERY_CASE_EXPRESSION_TYPE_INVALID", "case expression type must be 'case_expression'")
	ErrCaseExpressionNoConditions           = common.NewSystemError("ERR_QUERY_CASE_EXPRESSION_NO_CONDITIONS", "case expression must have at least one condition")
	ErrCaseExpressionAliasEmpty             = common.NewSystemError("ERR_QUERY_CASE_EXPRESSION_ALIAS_EMPTY", "case expression alias cannot be empty")
	ErrProjectionComputedItemConflict       = common.NewSystemError("ERR_QUERY_PROJECTION_COMPUTED_ITEM_CONFLICT", "ProjectionComputedItem must have exactly one of ComputedFieldExpression or CaseExpression set")
	ErrDistinctConfigNil                    = common.NewSystemError("ERR_QUERY_DISTINCT_CONFIG_NIL", "distinct configuration cannot be nil")
	ErrDistinctConfigMissingFields          = common.NewSystemError("ERR_QUERY_DISTINCT_CONFIG_MISSING_FIELDS", "distinct configuration must specify 'is_distinct' or 'fields'")
	ErrDistinctConfigConflict               = common.NewSystemError("ERR_QUERY_DISTINCT_CONFIG_CONFLICT", "distinct configuration cannot specify both 'is_distinct' and 'fields'")
	ErrDistinctFieldNameEmpty               = common.NewSystemError("ERR_QUERY_DISTINCT_FIELD_NAME_EMPTY", "distinct field name cannot be empty")
	ErrAggregationConfigEmpty               = common.NewSystemError("ERR_QUERY_AGGREGATION_CONFIG_EMPTY", "aggregation configuration cannot be empty if specified")
	ErrAggregationFieldEmpty                = common.NewSystemError("ERR_QUERY_AGGREGATION_FIELD_EMPTY", "aggregation field cannot be empty for non-count aggregations")
	ErrAggregationGroupFieldEmpty           = common.NewSystemError("ERR_QUERY_AGGREGATION_GROUP_FIELD_EMPTY", "aggregation group field cannot be empty")
	ErrInvalidFilterNoConditionGroupText    = common.NewSystemError("ERR_QUERY_INVALID_FILTER_NO_CONDITION_GROUP_TEXT", "invalid filter: no condition, group, or text match specified")
	ErrInOperatorRequiresSliceOrArray       = common.NewSystemError("ERR_QUERY_IN_OPERATOR_REQUIRES_SLICE_OR_ARRAY", "IN operator requires a slice or array value as the comparison target")
	ErrContainsOperatorRequiresString       = common.NewSystemError("ERR_QUERY_CONTAINS_OPERATOR_REQUIRES_STRING", "CONTAINS operator requires string values for comparison target")
	ErrFunctionNotImplementedOrRegistered   = common.NewSystemError("ERR_QUERY_FUNCTION_NOT_IMPLEMENTED_OR_REGISTERED", "function not implemented or registered")
	ErrJoinConfigNil                        = common.NewSystemError("ERR_QUERY_JOIN_CONFIG_NIL", "join configuration cannot be nil")
	ErrUnsupportedJoinType                  = common.NewSystemError("ERR_QUERY_UNSUPPORTED_JOIN_TYPE", "unsupported join type")
	ErrTargetCannotBeNil                    = common.NewSystemError("ERR_QUERY_TARGET_CANNOT_BE_NIL", "target cannot be nil")
	ErrTargetNameEmptyStream                = common.NewSystemError("ERR_QUERY_TARGET_NAME_EMPTY_STREAM", "target name cannot be empty")
	ErrJoinConditionNil                     = common.NewSystemError("ERR_QUERY_JOIN_CONDITION_NIL", "join condition ('on') cannot be nil")

	// ErrDDLNotSupported is returned by SchemaManager methods when the backend
	// cannot perform the requested DDL operation in place.
	ErrDDLNotSupported = common.NewSystemError("ERR_QUERY_DDL_NOT_SUPPORTED", "this DDL operation is not supported by the backend")
)
