// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: schemas/products.schema.json
// Date: 2026-07-08T06:44:36Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// Products_0_0_0_to_1_0_0 returns a migration plan for Products_0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func Products_0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target_Products_1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: Products_0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target_Products_1_0_0 is the target schema serialized from schemas/products.schema.json.
var target_Products_1_0_0_json = []byte(`{"version":"1.0.0","name":"Products","fields":{"019f405a-e686-75b6-95da-737a99188596":{"name":"name","required":true,"unique":true,"type":"string"},"019f405a-e686-764c-839f-a217470c321c":{"name":"price","required":true,"type":"number"},"019f405a-e686-7658-b3c8-fd15c3db2889":{"name":"stock","required":true,"type":"integer"},"019f405a-e686-7663-b32a-ccbccfc18c52":{"name":"category","type":"string"}}}`)

func target_Products_1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target_Products_1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
