// Code generated by anansi schema migrate. DO NOT EDIT.
package migrations

import (
	"context"
	"fmt"

	"github.com/asaidimu/go-anansi/v7/core/persistence/base"
	"github.com/asaidimu/go-anansi/v7/core/schema/definition"
)

// Migration describes a single schema migration.
type Migration struct {
	Collection string
	From       string
	To         string
	File       string
	Plan       func() *base.MigrationPlan
}

// All is the complete list of registered migrations in order.
var All = []Migration{
	{Collection: "Products", From: "0.0.0", To: "1.0.0", File: "019f4078-a5c3-795c-ae90-ac15750f5ffb_Products_major.go", Plan: Products_0_0_0_to_1_0_0},
	{Collection: "Products", From: "1.0.0", To: "1.1.0", File: "019f4079-e76e-704d-86eb-c90dbb3ffc69_Products_minor.go", Plan: Products_1_0_0_to_1_1_0},
}

// Apply reconciles the database with every registered migration.
//
// For each collection:
//   - If it does not exist, it is created from the first migration's
//     target schema, then remaining migrations are applied in order.
//   - If it exists at a version that matches a migration's From, that
//     migration (and any subsequent pending ones) is applied.
//
// Usage:
//
//	p, cleanup := anansi.Playground(...)
//	defer cleanup()
//	migrations.Apply(ctx, p)
func Apply(ctx context.Context, p base.Persistence) error {
	collMigrations := make(map[string][]Migration)
	for _, m := range All {
		collMigrations[m.Collection] = append(collMigrations[m.Collection], m)
	}

	for _, ms := range collMigrations {
		name := ms[0].Collection

		exists, err := p.HasCollection(ctx, name)
		if err != nil {
			return fmt.Errorf("check %s: %w", name, err)
		}

		if !exists {
			// Bootstrap from the first migration's target, then apply the rest.
			first := ms[0].Plan().Target
			if err := p.CreateCollections(ctx, []*definition.Schema{first}); err != nil {
				return fmt.Errorf("create %s: %w", name, err)
			}
			ms = ms[1:] // don't re-apply the bootstrap migration
		}

		for _, m := range ms {
			sc, err := p.Schema(ctx, name)
			if err != nil {
				return fmt.Errorf("schema %s: %w", name, err)
			}
			if sc.Version.String() != m.From {
				continue
			}
			plan := m.Plan()
			if _, err := p.Migrate(ctx, name, plan, nil); err != nil {
				return fmt.Errorf("migrate %s %s->%s: %w", name, m.From, m.To, err)
			}
		}
	}
	return nil
}
