// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: schemas/example.schema.json
package migrations

import (
	"github.com/asaidimu/go-anansi/v7/core/persistence/base"
	"github.com/asaidimu/go-anansi/v7/core/schema/definition"
)

// Example_0_0_0_to_0_1_0 returns a migration plan (0.0.0 → 0.1.0).
func Example_0_0_0_to_0_1_0() *base.MigrationPlan {
	m := &base.MigrationPlan{
		Description: "initial schema",
		Target:      target_Example_0_1_0(),
		VersionBump: definition.BumpMinor,
	}
	return m
}

var target_Example_0_1_0_json = []byte("{\n  \"name\": \"Example\",\n  \"description\": \"Example schema — replace with your own\",\n  \"fields\": {\n    \"019d7775-6563-7c55-a6f3-ac8f087d89d1\": {\n      \"name\": \"name\",\n      \"type\": \"string\",\n      \"required\": true\n    }\n  }\n}")

func target_Example_0_1_0() *definition.Schema {
	s, err := definition.FromJSON(target_Example_0_1_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
