package golang

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"strings"
	"unicode"
)

// Schema structures conforming to schema.json meta-schema
type FieldDefinition struct {
	Name     string          `json:"name"`
	Type     string          `json:"type"`
	Required bool            `json:"required,omitempty"`
	Nullable bool            `json:"nullable,omitempty"`
	Schema   json.RawMessage `json:"schema,omitempty"`
}

type NestedSchemaDefinition struct {
	Name   string                     `json:"name"`
	Type   string                     `json:"type,omitempty"`
	Fields map[string]FieldDefinition `json:"fields,omitempty"`
	Values []interface{}              `json:"values,omitempty"`
	Schema json.RawMessage            `json:"schema,omitempty"`
}

type SchemaDefinition struct {
	Name    string                            `json:"name"`
	Version string                            `json:"version"`
	Fields  map[string]FieldDefinition        `json:"fields"`
	Schemas map[string]NestedSchemaDefinition `json:"schemas,omitempty"`
}

type SchemaRef struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

type CodeGenerator struct {
	Schema    SchemaDefinition
	SchemaMap map[string]NestedSchemaDefinition
	Buf       bytes.Buffer
}

func (g *CodeGenerator) Generate(pkgName string) ([]byte, error) {
	g.Buf.Reset()

	g.Buf.WriteString(fmt.Sprintf("// Code generated by Schema Codegen. DO NOT EDIT.\npackage %s\n\n", pkgName))
	g.Buf.WriteString("import (\n")
	g.Buf.WriteString("\t\"bytes\"\n")
	g.Buf.WriteString("\t\"fmt\"\n")
	g.Buf.WriteString("\t\"strconv\"\n")
	g.Buf.WriteString(")\n\n")

	// Emit zero-allocation static byte helper functions
	g.emitHelpers()

	// 1. Generate Root Struct & Codecs
	g.generateObjectCodec(g.Schema.Name, g.Schema.Fields)

	// 2. Generate Nested Object Structs & Union Structs
	for _, nested := range g.Schema.Schemas {
		if len(nested.Fields) > 0 {
			g.generateObjectCodec(nested.Name, nested.Fields)
		}
	}

	formatted, err := format.Source(g.Buf.Bytes())
	if err != nil {
		return g.Buf.Bytes(), fmt.Errorf("gofmt error: %w (source code printed)", err)
	}
	return formatted, nil
}

func (g *CodeGenerator) generateObjectCodec(structName string, fields map[string]FieldDefinition) {
	structName = exportName(structName)

	// --- Struct Declaration ---
	g.Buf.WriteString(fmt.Sprintf("type %s struct {\n", structName))
	for _, f := range fields {
		goType, _ := g.resolveGoType(f)
		g.Buf.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"` \n", exportName(f.Name), goType, f.Name))
	}
	g.Buf.WriteString("}\n\n")

	// --- MarshalJSON (Zero Allocation, Direct Append) ---
	g.Buf.WriteString(fmt.Sprintf("func (m *%s) MarshalJSON() ([]byte, error) {\n", structName))
	g.Buf.WriteString("\tif m == nil { return []byte(\"null\"), nil }\n")
	g.Buf.WriteString("\tbuf := make([]byte, 0, 256)\n")
	g.Buf.WriteString("\tbuf = append(buf, '{')\n")
	g.Buf.WriteString("\tfirst := true\n\n")

	for _, f := range fields {
		fieldName := fmt.Sprintf("m.%s", exportName(f.Name))
		jsonKey := f.Name

		g.Buf.WriteString("\tif !first { buf = append(buf, ',') }\n")
		g.Buf.WriteString("\tfirst = false\n")
		g.Buf.WriteString(fmt.Sprintf("\tbuf = append(buf, %q...)\n", fmt.Sprintf("%q:", jsonKey)))

		g.emitFieldMarshal(f, fieldName)
	}

	g.Buf.WriteString("\tbuf = append(buf, '}')\n")
	g.Buf.WriteString("\treturn buf, nil\n")
	g.Buf.WriteString("}\n\n")

	// --- UnmarshalJSON (Reflection-Free Byte Scanner) ---
	g.Buf.WriteString(fmt.Sprintf("func (m *%s) UnmarshalJSON(data []byte) error {\n", structName))
	g.Buf.WriteString("\tif string(data) == \"null\" || len(data) == 0 { return nil }\n")
	g.Buf.WriteString("\tif data[0] != '{' { return fmt.Errorf(\"expected '{'\") }\n")
	g.Buf.WriteString("\tdata = bytes.TrimSpace(data[1 : len(data)-1])\n")
	g.Buf.WriteString("\tfor len(data) > 0 {\n")
	g.Buf.WriteString("\t\tkey, val, rest, err := scanNextKV(data)\n")
	g.Buf.WriteString("\t\tif err != nil { return err }\n")
	g.Buf.WriteString("\t\tdata = rest\n")
	g.Buf.WriteString("\t\tswitch string(key) {\n")

	for _, f := range fields {
		fieldName := fmt.Sprintf("m.%s", exportName(f.Name))
		g.Buf.WriteString(fmt.Sprintf("\t\tcase %q:\n", f.Name))
		g.emitFieldUnmarshal(f, fieldName)
	}

	g.Buf.WriteString("\t\t}\n")
	g.Buf.WriteString("\t}\n")
	g.Buf.WriteString("\treturn nil\n")
	g.Buf.WriteString("}\n\n")
}

func (g *CodeGenerator) emitFieldMarshal(f FieldDefinition, fieldName string) {
	switch f.Type {
	case "string":
		g.Buf.WriteString(fmt.Sprintf("\tbuf = strconv.AppendQuote(buf, %s)\n", fieldName))
	case "integer":
		g.Buf.WriteString(fmt.Sprintf("\tbuf = strconv.AppendInt(buf, int64(%s), 10)\n", fieldName))
	case "number", "decimal":
		g.Buf.WriteString(fmt.Sprintf("\tbuf = strconv.AppendFloat(buf, float64(%s), 'f', -1, 64)\n", fieldName))
	case "boolean":
		g.Buf.WriteString(fmt.Sprintf("\tbuf = strconv.AppendBool(buf, %s)\n", fieldName))
	case "object":
		g.Buf.WriteString(fmt.Sprintf("\tb, err := %s.MarshalJSON()\n", fieldName))
		g.Buf.WriteString("\tif err != nil { return nil, err }\n")
		g.Buf.WriteString("\tbuf = append(buf, b...)\n")
	default:
		g.Buf.WriteString(fmt.Sprintf("\t// Custom/Union handling for %s\n", f.Name))
		g.Buf.WriteString(fmt.Sprintf("\tb, err := %s.MarshalJSON()\n", fieldName))
		g.Buf.WriteString("\tif err != nil { return nil, err }\n")
		g.Buf.WriteString("\tbuf = append(buf, b...)\n")
	}
}

func (g *CodeGenerator) emitFieldUnmarshal(f FieldDefinition, fieldName string) {
	switch f.Type {
	case "string":
		g.Buf.WriteString(fmt.Sprintf("\t\t\tstr, err := unquoteBytes(val)\n"))
		g.Buf.WriteString("\t\t\tif err != nil { return err }\n")
		g.Buf.WriteString(fmt.Sprintf("\t\t\t%s = str\n", fieldName))
	case "integer":
		g.Buf.WriteString(fmt.Sprintf("\t\t\tn, err := strconv.ParseInt(string(val), 10, 64)\n"))
		g.Buf.WriteString("\t\t\tif err != nil { return err }\n")
		g.Buf.WriteString(fmt.Sprintf("\t\t\t%s = n\n", fieldName))
	case "number", "decimal":
		g.Buf.WriteString(fmt.Sprintf("\t\t\tn, err := strconv.ParseFloat(string(val), 64)\n"))
		g.Buf.WriteString("\t\t\tif err != nil { return err }\n")
		g.Buf.WriteString(fmt.Sprintf("\t\t\t%s = n\n", fieldName))
	case "boolean":
		g.Buf.WriteString(fmt.Sprintf("\t\t\tb, err := strconv.ParseBool(string(val))\n"))
		g.Buf.WriteString("\t\t\tif err != nil { return err }\n")
		g.Buf.WriteString(fmt.Sprintf("\t\t\t%s = b\n", fieldName))
	case "object":
		g.Buf.WriteString(fmt.Sprintf("\t\t\tif err := %s.UnmarshalJSON(val); err != nil { return err }\n", fieldName))
	default:
		g.Buf.WriteString(fmt.Sprintf("\t\t\tif err := %s.UnmarshalJSON(val); err != nil { return err }\n", fieldName))
	}
}

func (g *CodeGenerator) resolveGoType(f FieldDefinition) (string, bool) {
	switch f.Type {
	case "string", "enum":
		return "string", false
	case "integer":
		return "int64", false
	case "number", "decimal":
		return "float64", false
	case "boolean":
		return "bool", false
	case "bytes":
		return "[]byte", false
	case "object":
		ref := g.parseSchemaRef(f.Schema)
		if target, ok := g.SchemaMap[ref.ID]; ok {
			return exportName(target.Name), false
		}
		return "interface{}", false
	default:
		return "interface{}", false
	}
}

func (g *CodeGenerator) parseSchemaRef(raw json.RawMessage) SchemaRef {
	var ref SchemaRef
	if len(raw) > 0 {
		_ = json.Unmarshal(raw, &ref)
	}
	return ref
}

func (g *CodeGenerator) emitHelpers() {
	g.Buf.WriteString(`// Fast zero-allocation byte lexer and string unquoter
func unquoteBytes(b []byte) (string, error) {
	if len(b) >= 2 && b[0] == '"' && b[len(b)-1] == '"' {
		return string(b[1 : len(b)-1]), nil
	}
	return "", fmt.Errorf("invalid string format")
}

func scanNextKV(data []byte) (key, val, rest []byte, err error) {
	data = bytes.TrimSpace(data)
	if len(data) == 0 {
		return nil, nil, nil, nil
	}
	if data[0] != '"' {
		return nil, nil, nil, fmt.Errorf("expected key quote")
	}
	endKey := bytes.IndexByte(data[1:], '"')
	if endKey == -1 {
		return nil, nil, nil, fmt.Errorf("malformed key string")
	}
	key = data[1 : endKey+1]
	data = bytes.TrimSpace(data[endKey+2:])
	if len(data) == 0 || data[0] != ':' {
		return nil, nil, nil, fmt.Errorf("expected ':' after key")
	}
	data = bytes.TrimSpace(data[1:])

	var depth int
	var inString bool
	var idx int
	for idx = 0; idx < len(data); idx++ {
		c := data[idx]
		if inString {
			if c == '"' && data[idx-1] != '\\' {
				inString = false
			}
			continue
		}
		switch c {
		case '"':
			inString = true
		case '{', '[':
			depth++
		case '}', ']':
			if depth == 0 {
				val = bytes.TrimSpace(data[:idx])
				rest = data[idx:]
				return key, val, rest, nil
			}
			depth--
		case ',':
			if depth == 0 {
				val = bytes.TrimSpace(data[:idx])
				rest = bytes.TrimSpace(data[idx+1:])
				return key, val, rest, nil
			}
		}
	}
	val = bytes.TrimSpace(data)
	return key, val, nil, nil
}
`)
}

func exportName(s string) string {
	if s == "" {
		return "Type"
	}
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsNumber(r)
	})
	for i, p := range parts {
		parts[i] = strings.Title(p)
	}
	return strings.Join(parts, "")
}
